# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False, verbose_name='经营人id')),
                ('operator_name', models.CharField(max_length=64, verbose_name='经营人姓名')),
                ('operator_tel', models.CharField(max_length=11, null=True, verbose_name='经营人联系方式')),
                ('operator_idcard', models.CharField(blank=True, max_length=18, null=True, verbose_name='经营人身份证')),
                ('operator_mark', models.TextField(blank=True, null=True, verbose_name='经营人变更备注')),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'permissions': (('User_information_can_be_modified', '可以修改用户信息'),),
            },
        ),
    ]
