# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False, verbose_name='门面id')),
                ('shop_address', models.CharField(max_length=45, verbose_name='门面地址')),
                ('shop_type', models.CharField(max_length=30, verbose_name='商铺类型')),
                ('shop_status', models.BooleanField(default=True, verbose_name='商铺状态（是否存在）')),
                ('shop_mark', models.TextField(blank=True, null=True, verbose_name='商铺变更备注')),
            ],
        ),
    ]
