# Generated by Django 2.1.10 on 2019-07-20 08:12

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='邮箱地址')),
                ('avator_sor', easy_thumbnails.fields.ThumbnailerImageField(default='avator/girls_02.jpg', upload_to=apps.accounts.models.user_directory_path, verbose_name='头像大图')),
                ('avator_sm', models.ImageField(default='avator/1557802240.384552.70x70.png', upload_to=apps.accounts.models.user_directory_path, verbose_name='头像缩略图')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('shelf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.BookShelf', verbose_name='用户对应书架')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
