# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0004_auto_20190619_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False, verbose_name='交租单编号')),
                ('start_date', models.DateField(verbose_name='周期始交日')),
                ('end_date', models.DateField(verbose_name='周期终交日')),
                ('pay_date', models.DateTimeField(verbose_name='交费日期')),
                ('should_amount', models.FloatField(verbose_name='应交费用')),
                ('pay_amount', models.FloatField(verbose_name='实交费用')),
                ('arrears', models.FloatField(verbose_name='本周期欠费')),
                ('rental_mark', models.TextField(blank=True, null=True, verbose_name='交租变更备注')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_set', to='contract.Contract', verbose_name='合同外键')),
            ],
        ),
    ]
