# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['contract', '-start_date']},
        ),
    ]
