# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20190619_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='pay_amount',
            field=models.FloatField(verbose_name='周期实交费用'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='should_amount',
            field=models.FloatField(verbose_name='周期应交费用'),
        ),
    ]
