# Generated by Django 2.1.10 on 2019-07-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField()),
                ('down_load', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '小说热度',
                'verbose_name_plural': '小说热度',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=20)),
                ('brief_introduction', models.TextField()),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.CharField(blank=True, max_length=100)),
                ('section_num', models.TextField(null=True)),
                ('kind', models.CharField(max_length=50, null=True)),
                ('heat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Heat')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
    ]
