# Generated by Django 2.1.10 on 2019-07-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=10, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generalize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalize_name', models.CharField(blank=True, max_length=50, null=True)),
                ('generalize_picture', models.CharField(blank=True, max_length=200, null=True)),
                ('generalize_novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Novel')),
            ],
        ),
    ]
