# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oper', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False, verbose_name='合同id')),
                ('shop_name', models.CharField(max_length=24, verbose_name='商店名称')),
                ('start_time', models.DateTimeField(verbose_name='合同开始日')),
                ('end_time', models.DateTimeField(verbose_name='合同结束日')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='合同修改日')),
                ('contract_unit', models.CharField(default='元', max_length=10, verbose_name='租金单位')),
                ('contract_pay_fininshed', models.BooleanField(default=False, verbose_name='是否支付完成')),
                ('contract_reminder', models.BooleanField(default=True, verbose_name='是否提醒交租')),
                ('contract_reminder_day', models.IntegerField(blank=True, null=True, verbose_name='收租提醒日')),
                ('contract_rent', models.IntegerField(max_length=12, verbose_name='月租金')),
                ('pay_type', models.IntegerField(choices=[(0, '选择交租方式'), (1, '按月支付'), (2, '按季支付'), (3, '按年支付')], verbose_name='租金支付方式')),
                ('contract_status', models.IntegerField(choices=[(0, '选择合同状态'), (1, '合同期'), (2, '合同结束'), (3, '合同未开始'), (4, '毁约')], verbose_name='合同状态')),
                ('contract_mark', models.TextField(blank=True, null=True, verbose_name='合同变更备注')),
                ('operator', models.ManyToManyField(related_name='contract_set', to='oper.Operator', verbose_name='经营人外键')),
                ('shop', models.ManyToManyField(related_name='contract_set', to='shop.Shop', verbose_name='门面外键')),
            ],
        ),
    ]
