# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20190618_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_time',
            field=models.DateField(verbose_name='合同结束日'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='modify_time',
            field=models.DateField(auto_now=True, verbose_name='合同修改日'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_time',
            field=models.DateField(verbose_name='合同开始日'),
        ),
    ]
