# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20190618_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '选择交租方式'), (1, '按月支付'), (3, '按季支付'), (12, '按年支付')], verbose_name='租金支付方式'),
        ),
    ]
