# Generated by Django 2.1.10 on 2019-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='collect_chapters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
