# Generated by Django 2.1.10 on 2019-07-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_bookshelf_collect_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='collect_chapters',
        ),
    ]
